theme: jekyll-theme-minimal
title: "Automated Window Shade"
description: EGR 314 Team 301 - Samuel Barnett <br> Jaden Nahoi-Baricar <br> Sivanee Naghichetty Premkumar <br> Amy Joyce C. Valencia <br> Houyu Zhang

