theme: jekyll-theme-minimal
title: "Automated Window Shade"
description: EGR 314 Team 301 <br> Samuel Barnett <br> Jaden Nahoi-Baricar <br> Sivanee Naghichetty Premkumar <br> Amy Joyce C. Valencia <br> Houyu Zhang

![](vertopal_53e86d8e1b304e0fba1b8ab00a47e725/media/Angled.png)

